metadata:
  creationTimestamp: null
  labels:
    app: payment-api
  name: payment-api
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment-api
    spec:
      containers:
      - image: waldara/payment-api:1.0
        name: payment-api
        ports:
        - containerPort: 8080
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-api
  name: payment-svc
  namespace: webapps
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: payment-api
  type: NodePort

